.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. rain_qt test_rain_qt
clean: FORCE
	$(MAKE) -C .. rain_qt_clean test_rain_qt_clean
check: FORCE
	$(MAKE) -C .. test_rain_qt_check
rain-qt rain-qt.exe: FORCE
	 $(MAKE) -C .. rain_qt
apk: FORCE
	$(MAKE) -C .. rain_qt_apk
